spring:
  datasource:
    driverClassName: org.postgresql.Driver
    # url: jdbc:postgresql://localhost:5432/curry
    url: jdbc:postgresql://localhost:5433/curry
    username: postgres
    password: postgres
